## NumPy Cheat Sheet

In [1]:
# Import Numpy Library

import numpy as np

### Importing/Exporting

np.loadtxt('file.txt') 

np.genfromtxt('file.csv',delimiter=',')

np.savetxt('file.txt',arr,delimiter=' ')

np.savetxt('file.csv',arr,delimiter=',')


### Creating Arrays

In [3]:
np.array([1,2,3]) # 1D array

array([1, 2, 3])

In [4]:
np.array([(1,2,3), (4,5,6)]) # 2D array

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.zeros(3) # 1D array of length 3 all values set to 0

array([ 0.,  0.,  0.])

In [6]:
np.ones((3,4)) # 3x4 array with all values set to 1

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [7]:
np.eye(5) #5x5 array of 0 with 1 on diagonal (Identity matrix)


array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [8]:
np.linspace(0,100,6) # Array of 6 evenly divided values from 0 to 100

array([   0.,   20.,   40.,   60.,   80.,  100.])

In [9]:
np.arange(0,10,3) # Array of values from 0 to less than 10 with step 3

array([0, 3, 6, 9])

In [10]:
np.full((2,3),8) # 2x3 array with all values 8

array([[8, 8, 8],
       [8, 8, 8]])

In [11]:
np.random.rand(4,5) # 4x5 array of random floats between 0-1

array([[ 0.04641949,  0.96259045,  0.38697492,  0.09353108,  0.4206148 ],
       [ 0.89464856,  0.40914839,  0.60481716,  0.83062148,  0.22162912],
       [ 0.67482072,  0.76192151,  0.1446952 ,  0.42974495,  0.06139046],
       [ 0.58966681,  0.19732013,  0.01268843,  0.18365932,  0.70359376]])

In [12]:
np.random.rand(6,7)*100 # 6x7 array of random floats between 0-100

array([[ 70.04024841,  90.60575438,   2.00678029,  97.03548685,
         72.72171423,   3.13682653,  66.58648563],
       [ 93.46048262,  40.20857866,   6.59855822,   8.5729243 ,
          0.61024503,  30.95154122,  44.41553895],
       [ 22.35143304,  82.84312652,  74.60175178,  36.19489361,
         39.16666528,  62.75462431,  95.70974006],
       [ 78.49101838,  26.19332017,  95.16588844,  81.91387814,
         29.38080823,  22.04064472,  48.66022096],
       [ 88.86878421,   4.29158066,  89.56193124,  93.51841874,
         67.74160454,  73.4290879 ,   9.57488706],
       [  5.20390592,  49.5490702 ,  18.76493428,  84.95051138,
         22.65781706,  25.02567906,  39.17076906]])

In [13]:
np.random.randint(5,size=(2,3)) # 2x3 array with random ints between 0-4

array([[2, 0, 2],
       [4, 2, 2]])

### Copying/Sorting/Reshaping

np.copy(arr) #Copies arr to new memory


arr.view(dtype) #Creates view of arr elements with type dtype



arr.sort( ) #Sorts arr

arr.sort(axis=0) #Sorts specific axis of arr

two_d_arr.flatten( ) #Flattens 2D array two_d_arr to 1D array

arr.T #Transposes arr (rows become columns and vice versa)

arr.reshape(3,4) #Reshapes arr to 3 rows, 4 columns without changing data

arr.resize((5,6)) #Changes arr shape to 5x6 and fills new values with 0

### Adding/Removing Elements

np.append(arr,values) #Appends or adds values to the end of arr

np.insert(arr,3,values) #Inserts values into arr before index 3

np.delete(arr,2,axis=0) #Deletes row on index 2 of arr

np.delete(arr,4,axis=1) #Deletes column on index 4 of arr

### Combining/Splitting

np.concatenate((arr1,arr2), axis=0) #Adds arr2 as rows to the end of arr1

np.concatenate((arr1,arr2),axis=1) #Adds arr2 as columns to the end of arr1

np.split(arr,3) #Splits arr into 3 sub-arrays

np.hsplit(arr,5) #Splits arr horizontally on the 5th index

### Indexing/Slicing/Subsetting

arr[5] #Returns the elements at index 5

arr[2,5] #Returns the 2D array element on index [2] [5]

arr[1] = 4 #Assigns array element on index 1 the value 4

arr[1,3]=10 #Assigns array element on index[1] [3] the value 10

arr[0:3] #Returns the elements at indices 0,1,2

arr[0:3,4] #Returns the elements on rows 0,1,2 at column 4

arr[:2] #Returns the elements at indices 0,1 or the rows

arr[:,1] #Returns the elements at index 1 on all rows

arr<5 #Returns an array with boolean values

~arr #Inverts a boolean array

arr[arr<5] #Returns array elements smaller than 5

### Properties

arr.size #Returns number of elements in arr

arr.shape #Returns dimensions of arr (rows, columns)

arr.dtype #Returns type of elements in arr

arr.astype(dtype) #Convert arr elements to type dtype

arr.tolist() #Convert arr to a Python list

np.info(np.eye) #View documentation for np.eye (an example)

### Scalar Math

np.add(arr,1) #Add 1 to each array element

np.subtract(arr,2) #Subtract 2 from each array element

np.multiply(arr,3) #Multiply each array element by 3

np.divide(arr,5) #Divide each array element by 5

np.power(arr,5) #Raise each array element to the 5th power

### Vector Math

np.add(arr1,arr2) #Elementwise add arr1 and arr2

np.subtract(arr1,arr2) #Elementwise subtract arr2 from arr1

np.multiply(arr1,arr2) #Elementwise multiply arr1 by arr2

np.divide(arr1,arr2) #Elementwise divide arr1 by arr2

np.power(arr1,arr2) #Elementwise raise arr1 raised to the power of arr2

np.array_equal(arr1,arr2) #Returns 'True' if the arrays have the same elements and shape

np.sqrt(arr) #Square root of each element in the array object

np.sin(arr) #Sine of each element in the array object

np.log(arr) #Natural log of each element in the array object

np.abs(arr) #Absolute value of each element in the array object

np.ceil(arr) #Rounds up to the nearest integer

np.floor(arr) #Rounds down to the nearest integer

np.round(arr) #Rounds to the nearest integer

### Statistics

np.mean(arr,axis=0) #Returns mean along specific axis

arr.sum( ) #Returns sum of arr

arr.min( ) #Returns minimum value of arr

arr.max(axis=0) #Returns maximum value of specific axis

np.var(arr) #Returns the variance of array

np.std(arr,axis=1) #Returns standard deviation of specific axis

arr.corrcoef( ) #Returns correlation coefficient of array